version: "3.3"

services:

  flask:
      build: ./RappiOesteFlask
      container_name: flask
      restart: always
      environment:
        - APP_NAME=DieguitoRappi
        - DB_USERNAME=example
      expose:
        - 9089
      links:
        - mysql:mysql

  nginx:
      build: ./RappiOesteNginx
      container_name: nginx
      restart: always
      ports:
        - "8077:8077"

  mysql:
    image: mysql:8.0.18
    container_name: mysql-8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rappioeste
      MYSQL_USER: rapiuser
      MYSQL_PASSWORD: rapiuserpass
    ports:
      - "3307:3306"
    volumes:
      - ~/Workstation/mysql-rappi-data:/var/lib/mysql