version: "3.3"

services:

  flask:
      build: ./RappiOesteFlask
      container_name: flask
      restart: always
      environment:
        - APP_NAME=DieguitoRappi
        - DB_USERNAME=example
      expose:
        - 9089

  nginx:
      build: ./RappiOesteNginx
      container_name: nginx
      restart: always
      ports:
        - "8077:8077"
