INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (1, 'AEP', 'aeroparque', 'buenos aires', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (2, 'EZE', 'ezeiza', 'buenos aires', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (3, 'BRC', 'san carlos de bariloche', 'río negro', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (4, 'CTC', 'catamarca', 'catamarca', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (5, 'CRD', 'comodoro rivadavia', 'chubut', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (6, 'COR', 'córdoba', 'córdoba', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (7, 'EPA', 'el palomar', 'buenos aires', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (8, 'FMA', 'formosa', 'formosa', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (9, 'EQS', 'esquel', 'chubut', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (10, 'CPO', 'general pico', 'la pampa', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (11, 'IGR', 'iguazú', 'misiones', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (12, 'JUJ', 'jujuy', 'jujuy', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (13, 'IRJ', 'la rioja', 'la rioja', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (14, 'LGS', 'malargue', 'mendoza', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (15, 'MDQ', 'mar del plata', 'buenos aires', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (16, 'MDZ', 'mendoza', 'mendoza', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (17, 'PRA', 'paraná', 'entre ríos', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (18, 'PSS', 'posadas', 'misiones', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (19, 'PMY', 'puerto madryn', 'chubut', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (20, 'RCQ', 'reconquista', 'santa fé', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (21, 'RES', 'resistencias', 'chaco', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (22, 'RCU', 'río cuarto', 'córdoba', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (23, 'RGL', 'río gallegos', 'santa cruz', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (24, 'RGA', 'río grande', 'tierra del fuego', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (25, 'RHD', 'río hondo', 'santiago del estero', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (26, 'SLA', 'salta', 'salta', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (27, 'FDO', 'san fernando', 'buenos aires', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (28, 'UAQ', 'san juan', 'san juan', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (29, 'LUQ', 'san luis', 'san luis', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (30, 'AFA', 'san rafael', 'mendoza', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (31, 'RSA', 'santa rosa', 'la pampa', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (32, 'SDE', 'santiago del estero', 'santiago del estero', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (33, 'TUC', 'tucumán', 'tucumán', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (34, 'VDM', 'viedma', 'río negro', null, null, 1);
INSERT INTO rappioeste.airport (id, code, description, state, state_code, address, show_airport) VALUES (35, 'VME', 'villa mercedes', 'san luis', null, null, 1);