version: '3.3'

services:

  mysql:
    image: mysql:8.0.17
    restart: always
    container_name: mySQL-docker
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: "rootP4$"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "userP4$"
      MYSQL_DATABASE: "rappi-oeste"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    # Where our data will be persisted
    volumes:
      - ~/Workstation/Docker/volume/mysql-data:/var/lib/mysql
