version: "3.3"

services:

  node-js:
      build: ./Docker-RappiOeste/
      container_name: node-js
      restart: always
      ports:
        - "3000:3000"
      expose:
        - 3000
      links:
        - mysql:mysql

  flask:
      build: ./Docker-RappiOesteCGI/RappiOesteFlask
      container_name: flask
      restart: always
      environment:
        - APP_NAME=RappiOeste
        - DB_USERNAME=example
      expose:
        - 9089
      links:
        - mysql:mysql

  nginx:
      build: ./Docker-RappiOesteCGI/RappiOesteNginx
      container_name: nginx
      restart: always
      ports:
        - "8077:8077"

  mysql:
    image: mysql:8.0.18
    container_name: mysql-8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rappioeste
      MYSQL_USER: rapiuser
      MYSQL_PASSWORD: rapiuserpass
    ports:
      - "3307:3306"
    volumes:
      - ~/Workstation/distributedSys/mysql-rappi-data:/var/lib/mysql
